export interface Tool {
  id: string;
  name: string;
  description: string;
  icon: string;
  path: string;
  category: string;
  keywords: string[];
}

export const tools: Tool[] = [
  {
    id: "char-counter",
    name: "文字数カウンター",
    description: "テキストの文字数・単語数・行数をリアルタイムでカウント。全角・半角も区別して表示。",
    icon: "Aa",
    path: "/tools/char-counter",
    category: "テキスト",
    keywords: ["文字数カウント", "文字数", "ワードカウント", "文字数チェック"],
  },
  {
    id: "json-formatter",
    name: "JSON整形ツール",
    description: "JSONデータを見やすく整形・検証。シンタックスエラーも即座に検出。",
    icon: "{}",
    path: "/tools/json-formatter",
    category: "開発",
    keywords: ["JSON整形", "JSON検証", "JSONフォーマッター", "JSON変換"],
  },
  {
    id: "qr-generator",
    name: "QRコード生成",
    description: "URLやテキストからQRコードを瞬時に作成。PNG画像でダウンロード可能。",
    icon: "QR",
    path: "/tools/qr-generator",
    category: "画像",
    keywords: ["QRコード作成", "QRコード生成", "QRコード"],
  },
  {
    id: "password-gen",
    name: "パスワード生成",
    description: "安全なランダムパスワードを生成。長さ・文字種をカスタマイズ可能。",
    icon: "PW",
    path: "/tools/password-gen",
    category: "セキュリティ",
    keywords: ["パスワード生成", "ランダムパスワード", "安全なパスワード"],
  },
  {
    id: "base64",
    name: "Base64変換",
    description: "テキストをBase64にエンコード・デコード。日本語も完全対応。",
    icon: "B64",
    path: "/tools/base64",
    category: "開発",
    keywords: ["Base64変換", "Base64エンコード", "Base64デコード"],
  },
  {
    id: "url-encode",
    name: "URLエンコード/デコード",
    description: "URLの特殊文字をエンコード・デコード。日本語URLの変換に便利。",
    icon: "%",
    path: "/tools/url-encode",
    category: "開発",
    keywords: ["URLエンコード", "URLデコード", "パーセントエンコーディング"],
  },
  {
    id: "color-converter",
    name: "カラーコード変換",
    description: "HEX・RGB・HSLを相互変換。カラーピッカーで直感的に色を選択。",
    icon: "C",
    path: "/tools/color-converter",
    category: "デザイン",
    keywords: ["カラーコード変換", "HEX変換", "RGB変換", "色変換"],
  },
  {
    id: "text-diff",
    name: "テキスト差分比較",
    description: "2つのテキストの差分をハイライト表示。変更箇所が一目でわかる。",
    icon: "+-",
    path: "/tools/text-diff",
    category: "テキスト",
    keywords: ["テキスト差分", "テキスト比較", "diff", "文章比較"],
  },
  {
    id: "markdown-preview",
    name: "Markdownプレビュー",
    description: "Markdownをリアルタイムでプレビュー。コピー&ペーストですぐ確認。",
    icon: "MD",
    path: "/tools/markdown-preview",
    category: "テキスト",
    keywords: ["Markdownプレビュー", "マークダウン", "Markdown変換"],
  },
  {
    id: "text-replace",
    name: "テキスト一括置換",
    description: "テキスト内の文字列を一括置換。正規表現にも対応。",
    icon: "ab",
    path: "/tools/text-replace",
    category: "テキスト",
    keywords: ["テキスト置換", "文字列置換", "一括置換", "検索置換"],
  },
  {
    id: "zen-han",
    name: "半角全角変換",
    description: "テキストの半角・全角を一括変換。英数字・記号・スペースに対応。",
    icon: "Ａa",
    path: "/tools/zen-han",
    category: "テキスト",
    keywords: ["半角全角変換", "全角半角", "半角変換", "全角変換"],
  },
  {
    id: "hash-gen",
    name: "ハッシュ生成",
    description: "SHA-1、SHA-256、SHA-512等のハッシュ値をテキストから即座に生成。",
    icon: "#",
    path: "/tools/hash-gen",
    category: "セキュリティ",
    keywords: ["ハッシュ生成", "SHA256", "SHA-1", "ハッシュ値"],
  },
  {
    id: "unix-time",
    name: "Unix時間変換",
    description: "Unixタイムスタンプと日時を相互変換。現在時刻もリアルタイム表示。",
    icon: "T",
    path: "/tools/unix-time",
    category: "開発",
    keywords: ["Unix時間変換", "タイムスタンプ変換", "エポック秒", "UNIX時間"],
  },
  {
    id: "byte-counter",
    name: "バイト数カウント",
    description: "テキストのバイト数をUTF-8、UTF-16、Shift-JISで計算。文字コード判定にも。",
    icon: "01",
    path: "/tools/byte-counter",
    category: "開発",
    keywords: ["バイト数", "文字コード判定", "バイトカウント", "文字コード変換"],
  },
  {
    id: "regex-tester",
    name: "正規表現テスター",
    description: "正規表現パターンをリアルタイムでテスト。マッチ結果をハイライト表示。",
    icon: ".*",
    path: "/tools/regex-tester",
    category: "開発",
    keywords: ["正規表現テスト", "regex", "正規表現チェッカー", "パターンマッチ"],
  },
  {
    id: "html-escape",
    name: "HTMLエスケープ",
    description: "HTML特殊文字をエスケープ・アンエスケープ。XSS対策にも。",
    icon: "<>",
    path: "/tools/html-escape",
    category: "開発",
    keywords: ["HTMLエスケープ", "HTMLアンエスケープ", "特殊文字変換", "XSS対策"],
  },
  {
    id: "word-counter",
    name: "SNS文字数チェッカー",
    description: "Twitter、Instagram、YouTube等の文字数制限をリアルタイムでチェック。",
    icon: "📱",
    path: "/tools/word-counter",
    category: "テキスト",
    keywords: ["SNS文字数", "Twitter文字数", "Instagram文字数", "文字数制限"],
  },
  {
    id: "lorem-ipsum",
    name: "ダミーテキスト生成",
    description: "デザインやレイアウト確認用のダミーテキストを生成。日本語・英語対応。",
    icon: "Tx",
    path: "/tools/lorem-ipsum",
    category: "テキスト",
    keywords: ["ダミーテキスト", "Lorem Ipsum", "テスト文章", "サンプルテキスト"],
  },
  {
    id: "json-to-csv",
    name: "JSON → CSV変換",
    description: "JSON配列をCSV形式に変換。ExcelやGoogleスプレッドシートに貼り付け可能。",
    icon: "📊",
    path: "/tools/json-to-csv",
    category: "開発",
    keywords: ["JSON CSV変換", "JSON to CSV", "JSONからCSV", "データ変換"],
  },
  {
    id: "aspect-ratio",
    name: "アスペクト比計算",
    description: "画像・動画のアスペクト比を計算。SNSや動画サイトの推奨サイズも一覧表示。",
    icon: "⊞",
    path: "/tools/aspect-ratio",
    category: "デザイン",
    keywords: ["アスペクト比", "アスペクト比計算", "画像サイズ", "縦横比"],
  },
  {
    id: "number-converter",
    name: "進数変換",
    description: "2進数・8進数・10進数・16進数を相互変換。プログラミングに便利。",
    icon: "0x",
    path: "/tools/number-converter",
    category: "開発",
    keywords: ["進数変換", "2進数変換", "16進数変換", "基数変換"],
  },
  {
    id: "jwt-decoder",
    name: "JWTデコーダー",
    description: "JWTトークンをHeader・Payload・Signatureに分解してデコード表示。有効期限も確認。",
    icon: "JWT",
    path: "/tools/jwt-decoder",
    category: "開発",
    keywords: ["JWTデコード", "JWT解析", "JWTトークン", "JSON Web Token"],
  },
  {
    id: "cron-parser",
    name: "Cron式解説",
    description: "Cron式を日本語で解説。次の実行予定時刻やよく使うプリセット一覧も表示。",
    icon: "⏰",
    path: "/tools/cron-parser",
    category: "開発",
    keywords: ["Cron式解説", "crontab", "Cron変換", "スケジュール"],
  },
  {
    id: "encoding-detector",
    name: "文字コード判定",
    description: "テキストのバイト列から文字コードを推定。UTF-8、Shift_JIS、EUC-JP対応。16進ダンプ表示。",
    icon: "文",
    path: "/tools/encoding-detector",
    category: "テキスト",
    keywords: ["文字コード判定", "エンコーディング検出", "Shift_JIS判定", "UTF-8判定"],
  },
  {
    id: "ip-info",
    name: "IPアドレス情報",
    description: "IPv4/IPv6のクラス判定、CIDR計算、サブネット情報、バイナリ表現を表示。",
    icon: "IP",
    path: "/tools/ip-info",
    category: "開発",
    keywords: ["IPアドレス計算", "CIDR計算", "サブネット計算", "ネットワーク計算"],
  },
  {
    id: "uuid-gen",
    name: "UUID生成",
    description: "UUID（GUID）をワンクリックで生成。v4ランダムUUIDを一括生成。コピー可能。",
    icon: "ID",
    path: "/tools/uuid-gen",
    category: "開発",
    keywords: ["UUID生成", "GUID生成", "ランダムID", "ユニークID"],
  },
  {
    id: "csv-to-json",
    name: "CSV → JSON変換",
    description: "CSVデータをJSON形式に変換。ヘッダー自動検出、区切り文字指定対応。",
    icon: "📋",
    path: "/tools/csv-to-json",
    category: "開発",
    keywords: ["CSV JSON変換", "CSV to JSON", "CSVからJSON", "データ変換"],
  },
  {
    id: "yaml-json",
    name: "YAML ⇔ JSON変換",
    description: "YAMLとJSONを相互変換。Docker Compose・Kubernetes設定ファイルの変換に。",
    icon: "YJ",
    path: "/tools/yaml-json",
    category: "開発",
    keywords: ["YAML変換", "YAML JSON", "YAML to JSON", "設定ファイル変換"],
  },
  {
    id: "sql-formatter",
    name: "SQL整形",
    description: "SQLクエリを見やすく整形・フォーマット。インデント付きで可読性アップ。",
    icon: "SQL",
    path: "/tools/sql-formatter",
    category: "開発",
    keywords: ["SQL整形", "SQLフォーマッター", "SQL beautify", "クエリ整形"],
  },
  {
    id: "css-minify",
    name: "CSS圧縮・整形",
    description: "CSSを圧縮（ミニファイ）して軽量化、または整形して可読性向上。削減率も表示。",
    icon: "CSS",
    path: "/tools/css-minify",
    category: "開発",
    keywords: ["CSS圧縮", "CSSミニファイ", "CSS整形", "CSS minify"],
  },
  {
    id: "emoji-search",
    name: "絵文字検索",
    description: "絵文字を日本語キーワードで検索してワンクリックコピー。SNS・チャットに便利。",
    icon: "😀",
    path: "/tools/emoji-search",
    category: "テキスト",
    keywords: ["絵文字検索", "emoji検索", "絵文字コピー", "顔文字"],
  },
  {
    id: "timestamp-calc",
    name: "日時計算",
    description: "日付の差分計算、日数の加算・減算。経過日数・残り日数の確認に。",
    icon: "📅",
    path: "/tools/timestamp-calc",
    category: "開発",
    keywords: ["日付計算", "日数計算", "日時差分", "経過日数"],
  },
  {
    id: "slug-gen",
    name: "スラッグ生成",
    description: "テキストからURL用のスラッグを生成。SEOに最適なURLを簡単作成。",
    icon: "🔗",
    path: "/tools/slug-gen",
    category: "開発",
    keywords: ["スラッグ生成", "URL slug", "SEO URL", "パーマリンク"],
  },
  {
    id: "text-escape",
    name: "文字列エスケープ",
    description: "JSON・JavaScript・SQL・CSV・XMLの文字列エスケープ・アンエスケープ。",
    icon: "\\",
    path: "/tools/text-escape",
    category: "開発",
    keywords: ["文字列エスケープ", "JSONエスケープ", "SQLエスケープ", "エスケープ変換"],
  },
  {
    id: "html-to-md",
    name: "HTML → Markdown変換",
    description: "HTMLコードをMarkdown形式に変換。ブログ移行やドキュメント変換に便利。",
    icon: "H→M",
    path: "/tools/html-to-md",
    category: "テキスト",
    keywords: ["HTML Markdown変換", "HTMLからMarkdown", "HTML to MD", "マークダウン変換"],
  },
  {
    id: "text-case",
    name: "テキスト変換",
    description: "大文字・小文字・キャメルケース・スネークケース・ケバブケース等に一括変換。",
    icon: "Aa",
    path: "/tools/text-case",
    category: "テキスト",
    keywords: ["大文字変換", "小文字変換", "キャメルケース", "スネークケース"],
  },
  {
    id: "xml-formatter",
    name: "XML整形",
    description: "XMLデータを見やすく整形・フォーマット。圧縮（ミニファイ）にも対応。",
    icon: "XML",
    path: "/tools/xml-formatter",
    category: "開発",
    keywords: ["XML整形", "XMLフォーマッター", "XML beautify", "XML圧縮"],
  },
  {
    id: "url-parser",
    name: "URL解析",
    description: "URLを構成要素に分解表示。クエリパラメータの一覧化も。",
    icon: "🔍",
    path: "/tools/url-parser",
    category: "開発",
    keywords: ["URL解析", "URL分解", "URLパーサー", "クエリパラメータ"],
  },
  {
    id: "chmod-calc",
    name: "Chmod計算機",
    description: "Linuxのファイルパーミッションを数値⇔シンボル形式で相互変換。",
    icon: "🔒",
    path: "/tools/chmod-calc",
    category: "開発",
    keywords: ["chmod計算", "パーミッション変換", "Linuxパーミッション", "ファイル権限"],
  },
  {
    id: "line-sort",
    name: "行ソート・重複削除",
    description: "テキストの行を並べ替え、重複行の削除、空行の除去も対応。",
    icon: "↕",
    path: "/tools/line-sort",
    category: "テキスト",
    keywords: ["行ソート", "テキストソート", "重複削除", "行の並べ替え"],
  },
  {
    id: "gradient-gen",
    name: "CSSグラデーション生成",
    description: "CSSグラデーションを視覚的に作成。線形・放射状対応。プリセット付き。",
    icon: "🎨",
    path: "/tools/gradient-gen",
    category: "デザイン",
    keywords: ["CSSグラデーション", "グラデーション生成", "CSS gradient", "背景グラデーション"],
  },
  {
    id: "box-shadow-gen",
    name: "CSSボックスシャドウ生成",
    description: "box-shadowをスライダーで直感操作。複数レイヤー・プリセット対応。",
    icon: "🔲",
    path: "/tools/box-shadow-gen",
    category: "デザイン",
    keywords: ["box-shadow", "CSSシャドウ", "ボックスシャドウ", "CSS影"],
  },
  {
    id: "meta-tag-gen",
    name: "メタタグ生成",
    description: "SEO・SNS対応のHTMLメタタグを入力するだけで生成。Google検索プレビュー付き。",
    icon: "🏷",
    path: "/tools/meta-tag-gen",
    category: "開発",
    keywords: ["メタタグ生成", "SEOメタタグ", "OGPタグ", "Twitter Card"],
  },
  {
    id: "md-table-gen",
    name: "Markdownテーブル生成",
    description: "MarkdownのテーブルをGUIで簡単作成。CSV貼り付けにも対応。",
    icon: "📊",
    path: "/tools/md-table-gen",
    category: "テキスト",
    keywords: ["Markdownテーブル", "Markdown表", "テーブル生成", "Markdown table"],
  },
  {
    id: "gitignore-gen",
    name: ".gitignore生成",
    description: "言語・フレームワークを選ぶだけで.gitignoreファイルを自動生成。",
    icon: "Git",
    path: "/tools/gitignore-gen",
    category: "開発",
    keywords: [".gitignore生成", "gitignore作成", "gitignoreテンプレート", "Git設定"],
  },
  {
    id: "word-freq",
    name: "単語出現頻度",
    description: "テキスト内の単語・文字の出現頻度をカウント。SEO・文章分析に。",
    icon: "📈",
    path: "/tools/word-freq",
    category: "テキスト",
    keywords: ["単語頻度", "出現頻度", "テキスト分析", "キーワード密度"],
  },
  {
    id: "punycode",
    name: "Punycode変換",
    description: "日本語ドメインとPunycode（xn--形式）を相互変換。IDN確認に。",
    icon: "🌐",
    path: "/tools/punycode",
    category: "開発",
    keywords: ["Punycode変換", "日本語ドメイン", "IDN変換", "国際化ドメイン"],
  },
  {
    id: "json-path",
    name: "JSONPathテスター",
    description: "JSONデータからパス指定で値を抽出。API開発・デバッグに。",
    icon: "$..",
    path: "/tools/json-path",
    category: "開発",
    keywords: ["JSONPath", "JSON抽出", "JSONクエリ", "API デバッグ"],
  },
  {
    id: "og-preview",
    name: "OGPプレビュー",
    description: "OGPメタタグの情報でTwitter・Facebook等のシェア表示をプレビュー。",
    icon: "👁",
    path: "/tools/og-preview",
    category: "開発",
    keywords: ["OGPプレビュー", "SNSシェア", "OGP確認", "Twitter Card確認"],
  },
  {
    id: "image-base64",
    name: "画像Base64変換",
    description: "画像ファイルをBase64に変換。Data URI形式でHTML・CSSに埋め込み可能。",
    icon: "🖼",
    path: "/tools/image-base64",
    category: "デザイン",
    keywords: ["画像Base64", "画像エンコード", "Data URI", "画像埋め込み"],
  },
  {
    id: "age-calc",
    name: "年齢計算",
    description: "生年月日から現在の年齢を計算。年月日・日数・和暦表示。次の誕生日までのカウントダウンも。",
    icon: "🎂",
    path: "/tools/age-calc",
    category: "テキスト",
    keywords: ["年齢計算", "生年月日", "誕生日", "和暦変換"],
  },
  {
    id: "romaji",
    name: "ローマ字変換",
    description: "ひらがな・カタカナをローマ字に変換。ヘボン式・訓令式対応。パスポート申請にも。",
    icon: "Ａ",
    path: "/tools/romaji",
    category: "テキスト",
    keywords: ["ローマ字変換", "ひらがな", "カタカナ", "ヘボン式"],
  },
  {
    id: "unit-converter",
    name: "単位変換",
    description: "長さ・重さ・温度・データ容量・時間の単位をリアルタイム変換。",
    icon: "📏",
    path: "/tools/unit-converter",
    category: "開発",
    keywords: ["単位変換", "メートル変換", "温度変換", "データ容量"],
  },
  {
    id: "json-to-ts",
    name: "JSON→TypeScript型変換",
    description: "JSONデータからTypeScriptのインターフェース・型定義を自動生成。",
    icon: "TS",
    path: "/tools/json-to-ts",
    category: "開発",
    keywords: ["JSON TypeScript", "型定義生成", "interface生成", "TypeScript変換"],
  },
  {
    id: "flexbox-gen",
    name: "CSS Flexbox生成",
    description: "Flexboxレイアウトを視覚的に作成。direction・justify・align等を直感操作。",
    icon: "⬜",
    path: "/tools/flexbox-gen",
    category: "デザイン",
    keywords: ["Flexbox", "CSSレイアウト", "Flexboxジェネレーター", "CSS Flex"],
  },
  {
    id: "reading-time",
    name: "読了時間計算",
    description: "テキストの読了時間を計算。原稿用紙枚数・スピーチ時間も表示。ブロガー・ライター向け。",
    icon: "⏱",
    path: "/tools/reading-time",
    category: "テキスト",
    keywords: ["読了時間", "読書時間", "原稿用紙", "文字数計算"],
  },
  {
    id: "favicon-gen",
    name: "ファビコン生成",
    description: "テキストや絵文字からファビコンを生成。複数サイズ対応。ダウンロード可能。",
    icon: "⭐",
    path: "/tools/favicon-gen",
    category: "デザイン",
    keywords: ["ファビコン生成", "favicon", "アイコン作成", "Webアイコン"],
  },
  {
    id: "newline-converter",
    name: "改行コード変換",
    description: "LF・CRLF・CRの改行コードを相互変換。現在の改行コードも自動判定。",
    icon: "↵",
    path: "/tools/newline-converter",
    category: "開発",
    keywords: ["改行コード変換", "LF", "CRLF", "改行"],
  },
  {
    id: "robots-gen",
    name: "robots.txt生成",
    description: "robots.txtをGUIで簡単作成。WordPress・Next.js等のプリセット付き。",
    icon: "🤖",
    path: "/tools/robots-gen",
    category: "開発",
    keywords: ["robots.txt", "クローラー制御", "SEO", "検索エンジン"],
  },
  {
    id: "image-resize",
    name: "画像リサイズ",
    description: "画像のサイズ変更・圧縮。PNG・JPEG・WebP対応。品質調整プレビュー付き。",
    icon: "🖼",
    path: "/tools/image-resize",
    category: "画像",
    keywords: ["画像リサイズ", "画像圧縮", "サイズ変更", "画像縮小"],
  },
  {
    id: "bmi-calc",
    name: "BMI計算",
    description: "身長と体重からBMIを計算。日本肥満学会の基準で判定。理想体重も表示。",
    icon: "⚖",
    path: "/tools/bmi-calc",
    category: "計算",
    keywords: ["BMI計算", "体格指数", "肥満度", "理想体重", "ダイエット"],
  },
  {
    id: "tax-calc",
    name: "消費税計算",
    description: "消費税を計算。10%・8%軽減税率対応。税込み⇔税抜きの双方向計算。",
    icon: "💴",
    path: "/tools/tax-calc",
    category: "計算",
    keywords: ["消費税計算", "税込み", "税抜き", "軽減税率", "税額計算"],
  },
  {
    id: "loan-calc",
    name: "ローン計算",
    description: "借入金額・金利・返済期間からローンの月々返済額を計算。返済スケジュール付き。",
    icon: "🏠",
    path: "/tools/loan-calc",
    category: "計算",
    keywords: ["ローン計算", "住宅ローン", "返済シミュレーション", "借入計算"],
  },
  {
    id: "split-bill",
    name: "割り勘計算",
    description: "飲み会・食事の割り勘を計算。端数処理・傾斜配分にも対応。",
    icon: "🍻",
    path: "/tools/split-bill",
    category: "計算",
    keywords: ["割り勘", "割り勘計算", "飲み会", "精算", "費用分担"],
  },
  {
    id: "html-preview",
    name: "HTMLプレビュー",
    description: "HTMLコードをリアルタイムでプレビュー。CSS・JS対応。分割画面表示。",
    icon: "</>",
    path: "/tools/html-preview",
    category: "開発",
    keywords: ["HTMLプレビュー", "HTMLエディタ", "ライブプレビュー", "コードプレビュー"],
  },
  {
    id: "json-diff",
    name: "JSON比較",
    description: "2つのJSONデータを比較し、追加・削除・変更されたキーをハイライト表示。ネスト対応。",
    icon: "⇔",
    path: "/tools/json-diff",
    category: "開発",
    keywords: ["JSON比較", "JSON差分", "JSONdiff", "データ比較"],
  },
  {
    id: "color-palette",
    name: "カラーパレット生成",
    description: "ベースカラーから補色・類似色・トライアド等の配色パレットを自動生成。HEX・RGB対応。",
    icon: "🎨",
    path: "/tools/color-palette",
    category: "デザイン",
    keywords: ["カラーパレット", "配色生成", "補色", "カラースキーム"],
  },
  {
    id: "random-gen",
    name: "ランダム生成",
    description: "ランダムな数値・文字列・カラーコードを生成。範囲指定・文字種カスタマイズ対応。",
    icon: "🎲",
    path: "/tools/random-gen",
    category: "開発",
    keywords: ["ランダム生成", "乱数生成", "ランダム文字列", "ランダムカラー"],
  },
  {
    id: "mojibake-fix",
    name: "文字化け修復",
    description: "文字化けしたテキストを複数のエンコーディングパターンで復元。UTF-8・Shift_JIS・EUC-JP対応。",
    icon: "🔧",
    path: "/tools/mojibake-fix",
    category: "テキスト",
    keywords: ["文字化け修復", "文字化け", "エンコーディング", "文字コード変換"],
  },
  {
    id: "text-to-speech",
    name: "テキスト読み上げ",
    description: "テキストをブラウザの音声合成機能で読み上げ。日本語対応、速度・ピッチ調整可能。",
    icon: "🔊",
    path: "/tools/text-to-speech",
    category: "テキスト",
    keywords: ["テキスト読み上げ", "音声合成", "TTS", "Web Speech API"],
  },
  {
    id: "mercari-calc",
    name: "メルカリ利益計算機",
    description: "メルカリの手数料10%・全配送方法の送料・振込手数料を自動計算。送料比較表で最安配送も一目でわかる。",
    icon: "💰",
    path: "/tools/mercari-calc",
    category: "フリマ",
    keywords: ["メルカリ計算", "メルカリ手数料", "メルカリ利益", "メルカリ送料", "フリマ計算"],
  },
  {
    id: "side-job-tax",
    name: "副業の税金計算機",
    description: "副業したら手取りは結局いくら増える？本業年収と副業収入を入れるだけで所得税・住民税・確定申告の要否を瞬時計算。",
    icon: "📊",
    path: "/tools/side-job-tax",
    category: "お金",
    keywords: ["副業税金", "副業確定申告", "副業手取り", "副業計算", "所得税計算"],
  },
  {
    id: "oshi-trip-calc",
    name: "推し活遠征費計算",
    description: "推しに会いに行く遠征費用を一括計算！交通費・宿泊費・チケット代・グッズ代の総額と節約プランを自動提案。",
    icon: "🎤",
    path: "/tools/oshi-trip-calc",
    category: "推し活",
    keywords: ["推し活", "遠征費", "ライブ遠征", "推し活費用", "オタ活"],
  },
];
