export interface Tool {
  id: string;
  name: string;
  description: string;
  icon: string;
  path: string;
  category: string;
  keywords: string[];
  related?: string[]; // 関連ツールID（優先順）
}

export const tools: Tool[] = [
  {
    id: "char-counter",
    name: "文字数カウンター",
    description: "テキストの文字数・単語数・行数をリアルタイムでカウント。全角・半角も区別して表示。",
    icon: "Aa",
    path: "/tools/char-counter",
    category: "テキスト",
    keywords: ["文字数カウント", "文字数", "ワードカウント", "文字数チェック"],
  },
  {
    id: "json-formatter",
    name: "JSON整形ツール",
    description: "JSONデータを見やすく整形・検証。シンタックスエラーも即座に検出。",
    icon: "{}",
    path: "/tools/json-formatter",
    category: "開発",
    keywords: ["JSON整形", "JSON検証", "JSONフォーマッター", "JSON変換"],
  },
  {
    id: "qr-generator",
    name: "QRコード生成",
    description: "URLやテキストからQRコードを瞬時に作成。PNG画像でダウンロード可能。",
    icon: "QR",
    path: "/tools/qr-generator",
    category: "画像",
    keywords: ["QRコード作成", "QRコード生成", "QRコード"],
  },
  {
    id: "password-gen",
    name: "パスワード生成",
    description: "安全なランダムパスワードを生成。長さ・文字種をカスタマイズ可能。",
    icon: "PW",
    path: "/tools/password-gen",
    category: "セキュリティ",
    keywords: ["パスワード生成", "ランダムパスワード", "安全なパスワード"],
  },
  {
    id: "base64",
    name: "Base64変換",
    description: "テキストをBase64にエンコード・デコード。日本語も完全対応。",
    icon: "B64",
    path: "/tools/base64",
    category: "開発",
    keywords: ["Base64変換", "Base64エンコード", "Base64デコード"],
  },
  {
    id: "url-encode",
    name: "URLエンコード/デコード",
    description: "URLの特殊文字をエンコード・デコード。日本語URLの変換に便利。",
    icon: "%",
    path: "/tools/url-encode",
    category: "開発",
    keywords: ["URLエンコード", "URLデコード", "パーセントエンコーディング"],
  },
  {
    id: "color-converter",
    name: "カラーコード変換",
    description: "HEX・RGB・HSLを相互変換。カラーピッカーで直感的に色を選択。",
    icon: "C",
    path: "/tools/color-converter",
    category: "デザイン",
    keywords: ["カラーコード変換", "HEX変換", "RGB変換", "色変換"],
  },
  {
    id: "text-diff",
    name: "テキスト差分比較",
    description: "2つのテキストの差分をハイライト表示。変更箇所が一目でわかる。",
    icon: "+-",
    path: "/tools/text-diff",
    category: "テキスト",
    keywords: ["テキスト差分", "テキスト比較", "diff", "文章比較"],
  },
  {
    id: "markdown-preview",
    name: "Markdownプレビュー",
    description: "Markdownをリアルタイムでプレビュー。コピー&ペーストですぐ確認。",
    icon: "MD",
    path: "/tools/markdown-preview",
    category: "テキスト",
    keywords: ["Markdownプレビュー", "マークダウン", "Markdown変換"],
  },
  {
    id: "text-replace",
    name: "テキスト一括置換",
    description: "テキスト内の文字列を一括置換。正規表現にも対応。",
    icon: "ab",
    path: "/tools/text-replace",
    category: "テキスト",
    keywords: ["テキスト置換", "文字列置換", "一括置換", "検索置換"],
  },
  {
    id: "zen-han",
    name: "半角全角変換",
    description: "テキストの半角・全角を一括変換。英数字・記号・スペースに対応。",
    icon: "Ａa",
    path: "/tools/zen-han",
    category: "テキスト",
    keywords: ["半角全角変換", "全角半角", "半角変換", "全角変換"],
  },
  {
    id: "hash-gen",
    name: "ハッシュ生成",
    description: "SHA-1、SHA-256、SHA-512等のハッシュ値をテキストから即座に生成。",
    icon: "#",
    path: "/tools/hash-gen",
    category: "セキュリティ",
    keywords: ["ハッシュ生成", "SHA256", "SHA-1", "ハッシュ値"],
  },
  {
    id: "unix-time",
    name: "Unix時間変換",
    description: "Unixタイムスタンプと日時を相互変換。現在時刻もリアルタイム表示。",
    icon: "T",
    path: "/tools/unix-time",
    category: "開発",
    keywords: ["Unix時間変換", "タイムスタンプ変換", "エポック秒", "UNIX時間"],
  },
  {
    id: "byte-counter",
    name: "バイト数カウント",
    description: "テキストのバイト数をUTF-8、UTF-16、Shift-JISで計算。文字コード判定にも。",
    icon: "01",
    path: "/tools/byte-counter",
    category: "開発",
    keywords: ["バイト数", "文字コード判定", "バイトカウント", "文字コード変換"],
  },
  {
    id: "regex-tester",
    name: "正規表現テスター",
    description: "正規表現パターンをリアルタイムでテスト。マッチ結果をハイライト表示。",
    icon: ".*",
    path: "/tools/regex-tester",
    category: "開発",
    keywords: ["正規表現テスト", "regex", "正規表現チェッカー", "パターンマッチ"],
  },
  {
    id: "html-escape",
    name: "HTMLエスケープ",
    description: "HTML特殊文字をエスケープ・アンエスケープ。XSS対策にも。",
    icon: "<>",
    path: "/tools/html-escape",
    category: "開発",
    keywords: ["HTMLエスケープ", "HTMLアンエスケープ", "特殊文字変換", "XSS対策"],
  },
  {
    id: "word-counter",
    name: "SNS文字数チェッカー",
    description: "Twitter、Instagram、YouTube等の文字数制限をリアルタイムでチェック。",
    icon: "📱",
    path: "/tools/word-counter",
    category: "テキスト",
    keywords: ["SNS文字数", "Twitter文字数", "Instagram文字数", "文字数制限"],
  },
  {
    id: "lorem-ipsum",
    name: "ダミーテキスト生成",
    description: "デザインやレイアウト確認用のダミーテキストを生成。日本語・英語対応。",
    icon: "Tx",
    path: "/tools/lorem-ipsum",
    category: "テキスト",
    keywords: ["ダミーテキスト", "Lorem Ipsum", "テスト文章", "サンプルテキスト"],
  },
  {
    id: "json-to-csv",
    name: "JSON → CSV変換",
    description: "JSON配列をCSV形式に変換。ExcelやGoogleスプレッドシートに貼り付け可能。",
    icon: "📊",
    path: "/tools/json-to-csv",
    category: "開発",
    keywords: ["JSON CSV変換", "JSON to CSV", "JSONからCSV", "データ変換"],
  },
  {
    id: "aspect-ratio",
    name: "アスペクト比計算",
    description: "画像・動画のアスペクト比を計算。SNSや動画サイトの推奨サイズも一覧表示。",
    icon: "⊞",
    path: "/tools/aspect-ratio",
    category: "デザイン",
    keywords: ["アスペクト比", "アスペクト比計算", "画像サイズ", "縦横比"],
  },
  {
    id: "number-converter",
    name: "進数変換",
    description: "2進数・8進数・10進数・16進数を相互変換。プログラミングに便利。",
    icon: "0x",
    path: "/tools/number-converter",
    category: "開発",
    keywords: ["進数変換", "2進数変換", "16進数変換", "基数変換"],
  },
  {
    id: "jwt-decoder",
    name: "JWTデコーダー",
    description: "JWTトークンをHeader・Payload・Signatureに分解してデコード表示。有効期限も確認。",
    icon: "JWT",
    path: "/tools/jwt-decoder",
    category: "開発",
    keywords: ["JWTデコード", "JWT解析", "JWTトークン", "JSON Web Token"],
  },
  {
    id: "cron-parser",
    name: "Cron式解説",
    description: "Cron式を日本語で解説。次の実行予定時刻やよく使うプリセット一覧も表示。",
    icon: "⏰",
    path: "/tools/cron-parser",
    category: "開発",
    keywords: ["Cron式解説", "crontab", "Cron変換", "スケジュール"],
  },
  {
    id: "encoding-detector",
    name: "文字コード判定",
    description: "テキストのバイト列から文字コードを推定。UTF-8、Shift_JIS、EUC-JP対応。16進ダンプ表示。",
    icon: "文",
    path: "/tools/encoding-detector",
    category: "テキスト",
    keywords: ["文字コード判定", "エンコーディング検出", "Shift_JIS判定", "UTF-8判定"],
  },
  {
    id: "ip-info",
    name: "IPアドレス情報",
    description: "IPv4/IPv6のクラス判定、CIDR計算、サブネット情報、バイナリ表現を表示。",
    icon: "IP",
    path: "/tools/ip-info",
    category: "開発",
    keywords: ["IPアドレス計算", "CIDR計算", "サブネット計算", "ネットワーク計算"],
  },
  {
    id: "uuid-gen",
    name: "UUID生成",
    description: "UUID（GUID）をワンクリックで生成。v4ランダムUUIDを一括生成。コピー可能。",
    icon: "ID",
    path: "/tools/uuid-gen",
    category: "開発",
    keywords: ["UUID生成", "GUID生成", "ランダムID", "ユニークID"],
  },
  {
    id: "csv-to-json",
    name: "CSV → JSON変換",
    description: "CSVデータをJSON形式に変換。ヘッダー自動検出、区切り文字指定対応。",
    icon: "📋",
    path: "/tools/csv-to-json",
    category: "開発",
    keywords: ["CSV JSON変換", "CSV to JSON", "CSVからJSON", "データ変換"],
  },
  {
    id: "yaml-json",
    name: "YAML ⇔ JSON変換",
    description: "YAMLとJSONを相互変換。Docker Compose・Kubernetes設定ファイルの変換に。",
    icon: "YJ",
    path: "/tools/yaml-json",
    category: "開発",
    keywords: ["YAML変換", "YAML JSON", "YAML to JSON", "設定ファイル変換"],
  },
  {
    id: "sql-formatter",
    name: "SQL整形",
    description: "SQLクエリを見やすく整形・フォーマット。インデント付きで可読性アップ。",
    icon: "SQL",
    path: "/tools/sql-formatter",
    category: "開発",
    keywords: ["SQL整形", "SQLフォーマッター", "SQL beautify", "クエリ整形"],
  },
  {
    id: "css-minify",
    name: "CSS圧縮・整形",
    description: "CSSを圧縮（ミニファイ）して軽量化、または整形して可読性向上。削減率も表示。",
    icon: "CSS",
    path: "/tools/css-minify",
    category: "開発",
    keywords: ["CSS圧縮", "CSSミニファイ", "CSS整形", "CSS minify"],
  },
  {
    id: "emoji-search",
    name: "絵文字検索",
    description: "絵文字を日本語キーワードで検索してワンクリックコピー。SNS・チャットに便利。",
    icon: "😀",
    path: "/tools/emoji-search",
    category: "テキスト",
    keywords: ["絵文字検索", "emoji検索", "絵文字コピー", "顔文字"],
  },
  {
    id: "timestamp-calc",
    name: "日時計算",
    description: "日付の差分計算、日数の加算・減算。経過日数・残り日数の確認に。",
    icon: "📅",
    path: "/tools/timestamp-calc",
    category: "開発",
    keywords: ["日付計算", "日数計算", "日時差分", "経過日数"],
  },
  {
    id: "slug-gen",
    name: "スラッグ生成",
    description: "テキストからURL用のスラッグを生成。SEOに最適なURLを簡単作成。",
    icon: "🔗",
    path: "/tools/slug-gen",
    category: "開発",
    keywords: ["スラッグ生成", "URL slug", "SEO URL", "パーマリンク"],
  },
  {
    id: "text-escape",
    name: "文字列エスケープ",
    description: "JSON・JavaScript・SQL・CSV・XMLの文字列エスケープ・アンエスケープ。",
    icon: "\\",
    path: "/tools/text-escape",
    category: "開発",
    keywords: ["文字列エスケープ", "JSONエスケープ", "SQLエスケープ", "エスケープ変換"],
  },
  {
    id: "html-to-md",
    name: "HTML → Markdown変換",
    description: "HTMLコードをMarkdown形式に変換。ブログ移行やドキュメント変換に便利。",
    icon: "H→M",
    path: "/tools/html-to-md",
    category: "テキスト",
    keywords: ["HTML Markdown変換", "HTMLからMarkdown", "HTML to MD", "マークダウン変換"],
  },
  {
    id: "text-case",
    name: "テキスト変換",
    description: "大文字・小文字・キャメルケース・スネークケース・ケバブケース等に一括変換。",
    icon: "Aa",
    path: "/tools/text-case",
    category: "テキスト",
    keywords: ["大文字変換", "小文字変換", "キャメルケース", "スネークケース"],
  },
  {
    id: "xml-formatter",
    name: "XML整形",
    description: "XMLデータを見やすく整形・フォーマット。圧縮（ミニファイ）にも対応。",
    icon: "XML",
    path: "/tools/xml-formatter",
    category: "開発",
    keywords: ["XML整形", "XMLフォーマッター", "XML beautify", "XML圧縮"],
  },
  {
    id: "url-parser",
    name: "URL解析",
    description: "URLを構成要素に分解表示。クエリパラメータの一覧化も。",
    icon: "🔍",
    path: "/tools/url-parser",
    category: "開発",
    keywords: ["URL解析", "URL分解", "URLパーサー", "クエリパラメータ"],
  },
  {
    id: "chmod-calc",
    name: "Chmod計算機",
    description: "Linuxのファイルパーミッションを数値⇔シンボル形式で相互変換。",
    icon: "🔒",
    path: "/tools/chmod-calc",
    category: "開発",
    keywords: ["chmod計算", "パーミッション変換", "Linuxパーミッション", "ファイル権限"],
  },
  {
    id: "line-sort",
    name: "行ソート・重複削除",
    description: "テキストの行を並べ替え、重複行の削除、空行の除去も対応。",
    icon: "↕",
    path: "/tools/line-sort",
    category: "テキスト",
    keywords: ["行ソート", "テキストソート", "重複削除", "行の並べ替え"],
  },
  {
    id: "gradient-gen",
    name: "CSSグラデーション生成",
    description: "CSSグラデーションを視覚的に作成。線形・放射状対応。プリセット付き。",
    icon: "🎨",
    path: "/tools/gradient-gen",
    category: "デザイン",
    keywords: ["CSSグラデーション", "グラデーション生成", "CSS gradient", "背景グラデーション"],
  },
  {
    id: "box-shadow-gen",
    name: "CSSボックスシャドウ生成",
    description: "box-shadowをスライダーで直感操作。複数レイヤー・プリセット対応。",
    icon: "🔲",
    path: "/tools/box-shadow-gen",
    category: "デザイン",
    keywords: ["box-shadow", "CSSシャドウ", "ボックスシャドウ", "CSS影"],
  },
  {
    id: "meta-tag-gen",
    name: "メタタグ生成",
    description: "SEO・SNS対応のHTMLメタタグを入力するだけで生成。Google検索プレビュー付き。",
    icon: "🏷",
    path: "/tools/meta-tag-gen",
    category: "開発",
    keywords: ["メタタグ生成", "SEOメタタグ", "OGPタグ", "Twitter Card"],
  },
  {
    id: "md-table-gen",
    name: "Markdownテーブル生成",
    description: "MarkdownのテーブルをGUIで簡単作成。CSV貼り付けにも対応。",
    icon: "📊",
    path: "/tools/md-table-gen",
    category: "テキスト",
    keywords: ["Markdownテーブル", "Markdown表", "テーブル生成", "Markdown table"],
  },
  {
    id: "gitignore-gen",
    name: ".gitignore生成",
    description: "言語・フレームワークを選ぶだけで.gitignoreファイルを自動生成。",
    icon: "Git",
    path: "/tools/gitignore-gen",
    category: "開発",
    keywords: [".gitignore生成", "gitignore作成", "gitignoreテンプレート", "Git設定"],
  },
  {
    id: "word-freq",
    name: "単語出現頻度",
    description: "テキスト内の単語・文字の出現頻度をカウント。SEO・文章分析に。",
    icon: "📈",
    path: "/tools/word-freq",
    category: "テキスト",
    keywords: ["単語頻度", "出現頻度", "テキスト分析", "キーワード密度"],
  },
  {
    id: "punycode",
    name: "Punycode変換",
    description: "日本語ドメインとPunycode（xn--形式）を相互変換。IDN確認に。",
    icon: "🌐",
    path: "/tools/punycode",
    category: "開発",
    keywords: ["Punycode変換", "日本語ドメイン", "IDN変換", "国際化ドメイン"],
  },
  {
    id: "json-path",
    name: "JSONPathテスター",
    description: "JSONデータからパス指定で値を抽出。API開発・デバッグに。",
    icon: "$..",
    path: "/tools/json-path",
    category: "開発",
    keywords: ["JSONPath", "JSON抽出", "JSONクエリ", "API デバッグ"],
  },
  {
    id: "og-preview",
    name: "OGPプレビュー",
    description: "OGPメタタグの情報でTwitter・Facebook等のシェア表示をプレビュー。",
    icon: "👁",
    path: "/tools/og-preview",
    category: "開発",
    keywords: ["OGPプレビュー", "SNSシェア", "OGP確認", "Twitter Card確認"],
  },
  {
    id: "image-base64",
    name: "画像Base64変換",
    description: "画像ファイルをBase64に変換。Data URI形式でHTML・CSSに埋め込み可能。",
    icon: "🖼",
    path: "/tools/image-base64",
    category: "デザイン",
    keywords: ["画像Base64", "画像エンコード", "Data URI", "画像埋め込み"],
  },
  {
    id: "age-calc",
    name: "年齢計算",
    description: "生年月日から現在の年齢を計算。年月日・日数・和暦表示。次の誕生日までのカウントダウンも。",
    icon: "🎂",
    path: "/tools/age-calc",
    category: "テキスト",
    keywords: ["年齢計算", "生年月日", "誕生日", "和暦変換"],
  },
  {
    id: "romaji",
    name: "ローマ字変換",
    description: "ひらがな・カタカナをローマ字に変換。ヘボン式・訓令式対応。パスポート申請にも。",
    icon: "Ａ",
    path: "/tools/romaji",
    category: "テキスト",
    keywords: ["ローマ字変換", "ひらがな", "カタカナ", "ヘボン式"],
  },
  {
    id: "unit-converter",
    name: "単位変換",
    description: "長さ・重さ・温度・データ容量・時間の単位をリアルタイム変換。",
    icon: "📏",
    path: "/tools/unit-converter",
    category: "開発",
    keywords: ["単位変換", "メートル変換", "温度変換", "データ容量"],
  },
  {
    id: "json-to-ts",
    name: "JSON→TypeScript型変換",
    description: "JSONデータからTypeScriptのインターフェース・型定義を自動生成。",
    icon: "TS",
    path: "/tools/json-to-ts",
    category: "開発",
    keywords: ["JSON TypeScript", "型定義生成", "interface生成", "TypeScript変換"],
  },
  {
    id: "flexbox-gen",
    name: "CSS Flexbox生成",
    description: "Flexboxレイアウトを視覚的に作成。direction・justify・align等を直感操作。",
    icon: "⬜",
    path: "/tools/flexbox-gen",
    category: "デザイン",
    keywords: ["Flexbox", "CSSレイアウト", "Flexboxジェネレーター", "CSS Flex"],
  },
  {
    id: "reading-time",
    name: "読了時間計算",
    description: "テキストの読了時間を計算。原稿用紙枚数・スピーチ時間も表示。ブロガー・ライター向け。",
    icon: "⏱",
    path: "/tools/reading-time",
    category: "テキスト",
    keywords: ["読了時間", "読書時間", "原稿用紙", "文字数計算"],
  },
  {
    id: "favicon-gen",
    name: "ファビコン生成",
    description: "テキストや絵文字からファビコンを生成。複数サイズ対応。ダウンロード可能。",
    icon: "⭐",
    path: "/tools/favicon-gen",
    category: "デザイン",
    keywords: ["ファビコン生成", "favicon", "アイコン作成", "Webアイコン"],
  },
  {
    id: "newline-converter",
    name: "改行コード変換",
    description: "LF・CRLF・CRの改行コードを相互変換。現在の改行コードも自動判定。",
    icon: "↵",
    path: "/tools/newline-converter",
    category: "開発",
    keywords: ["改行コード変換", "LF", "CRLF", "改行"],
  },
  {
    id: "robots-gen",
    name: "robots.txt生成",
    description: "robots.txtをGUIで簡単作成。WordPress・Next.js等のプリセット付き。",
    icon: "🤖",
    path: "/tools/robots-gen",
    category: "開発",
    keywords: ["robots.txt", "クローラー制御", "SEO", "検索エンジン"],
  },
  {
    id: "image-resize",
    name: "画像リサイズ",
    description: "画像のサイズ変更・圧縮。PNG・JPEG・WebP対応。品質調整プレビュー付き。",
    icon: "🖼",
    path: "/tools/image-resize",
    category: "画像",
    keywords: ["画像リサイズ", "画像圧縮", "サイズ変更", "画像縮小"],
  },
  {
    id: "bmi-calc",
    name: "BMI計算",
    description: "身長と体重からBMIを計算。日本肥満学会の基準で判定。理想体重も表示。",
    icon: "⚖",
    path: "/tools/bmi-calc",
    category: "計算",
    keywords: ["BMI計算", "体格指数", "肥満度", "理想体重", "ダイエット"],
  },
  {
    id: "tax-calc",
    name: "消費税計算",
    description: "消費税を計算。10%・8%軽減税率対応。税込み⇔税抜きの双方向計算。",
    icon: "💴",
    path: "/tools/tax-calc",
    category: "計算",
    keywords: ["消費税計算", "税込み", "税抜き", "軽減税率", "税額計算"],
  },
  {
    id: "loan-calc",
    name: "ローン計算",
    description: "借入金額・金利・返済期間からローンの月々返済額を計算。返済スケジュール付き。",
    icon: "🏠",
    path: "/tools/loan-calc",
    category: "計算",
    keywords: ["ローン計算", "住宅ローン", "返済シミュレーション", "借入計算"],
  },
  {
    id: "split-bill",
    name: "割り勘計算",
    description: "飲み会・食事の割り勘を計算。端数処理・傾斜配分にも対応。",
    icon: "🍻",
    path: "/tools/split-bill",
    category: "計算",
    keywords: ["割り勘", "割り勘計算", "飲み会", "精算", "費用分担"],
  },
  {
    id: "html-preview",
    name: "HTMLプレビュー",
    description: "HTMLコードをリアルタイムでプレビュー。CSS・JS対応。分割画面表示。",
    icon: "</>",
    path: "/tools/html-preview",
    category: "開発",
    keywords: ["HTMLプレビュー", "HTMLエディタ", "ライブプレビュー", "コードプレビュー"],
  },
  {
    id: "json-diff",
    name: "JSON比較",
    description: "2つのJSONデータを比較し、追加・削除・変更されたキーをハイライト表示。ネスト対応。",
    icon: "⇔",
    path: "/tools/json-diff",
    category: "開発",
    keywords: ["JSON比較", "JSON差分", "JSONdiff", "データ比較"],
  },
  {
    id: "color-palette",
    name: "カラーパレット生成",
    description: "ベースカラーから補色・類似色・トライアド等の配色パレットを自動生成。HEX・RGB対応。",
    icon: "🎨",
    path: "/tools/color-palette",
    category: "デザイン",
    keywords: ["カラーパレット", "配色生成", "補色", "カラースキーム"],
  },
  {
    id: "random-gen",
    name: "ランダム生成",
    description: "ランダムな数値・文字列・カラーコードを生成。範囲指定・文字種カスタマイズ対応。",
    icon: "🎲",
    path: "/tools/random-gen",
    category: "開発",
    keywords: ["ランダム生成", "乱数生成", "ランダム文字列", "ランダムカラー"],
  },
  {
    id: "mojibake-fix",
    name: "文字化け修復",
    description: "文字化けしたテキストを複数のエンコーディングパターンで復元。UTF-8・Shift_JIS・EUC-JP対応。",
    icon: "🔧",
    path: "/tools/mojibake-fix",
    category: "テキスト",
    keywords: ["文字化け修復", "文字化け", "エンコーディング", "文字コード変換"],
  },
  {
    id: "text-to-speech",
    name: "テキスト読み上げ",
    description: "テキストをブラウザの音声合成機能で読み上げ。日本語対応、速度・ピッチ調整可能。",
    icon: "🔊",
    path: "/tools/text-to-speech",
    category: "テキスト",
    keywords: ["テキスト読み上げ", "音声合成", "TTS", "Web Speech API"],
  },
  {
    id: "mercari-calc",
    name: "メルカリ利益計算機",
    description: "メルカリの手数料10%・全配送方法の送料・振込手数料を自動計算。送料比較表で最安配送も一目でわかる。",
    icon: "💰",
    path: "/tools/mercari-calc",
    category: "フリマ",
    keywords: ["メルカリ計算", "メルカリ手数料", "メルカリ利益", "メルカリ送料", "フリマ計算"],
  },
  {
    id: "side-job-tax",
    name: "副業の税金計算機",
    description: "副業したら手取りは結局いくら増える？本業年収と副業収入を入れるだけで所得税・住民税・確定申告の要否を瞬時計算。",
    icon: "📊",
    path: "/tools/side-job-tax",
    category: "お金",
    keywords: ["副業税金", "副業確定申告", "副業手取り", "副業計算", "所得税計算"],
  },
  {
    id: "oshi-trip-calc",
    name: "推し活遠征費計算",
    description: "推しに会いに行く遠征費用を一括計算！交通費・宿泊費・チケット代・グッズ代の総額と節約プランを自動提案。",
    icon: "🎤",
    path: "/tools/oshi-trip-calc",
    category: "推し活",
    keywords: ["推し活", "遠征費", "ライブ遠征", "推し活費用", "オタ活"],
  },
  {
    id: "moving-cost",
    name: "引っ越し費用計算",
    description: "引っ越しの総費用を一括計算。業者代・敷金礼金・仲介手数料・家具代まで全て含めた見積もりと節約プラン。",
    icon: "🚛",
    path: "/tools/moving-cost",
    category: "お金",
    keywords: ["引っ越し費用", "引っ越し計算", "初期費用", "敷金礼金", "引越し見積もり"],
  },
  {
    id: "electricity-calc",
    name: "電気代計算ツール",
    description: "エアコン・ドライヤー・テレビなど家電ごとの電気代を瞬時に計算。月額シミュレーションと節約比較も。",
    icon: "⚡",
    path: "/tools/electricity-calc",
    category: "お金",
    keywords: ["電気代計算", "電気代", "消費電力", "電気料金", "家電電気代"],
  },
  {
    id: "salary-calc",
    name: "給料手取り計算",
    description: "年収から手取り額を瞬時に計算。所得税・住民税・社会保険料の内訳も一目でわかるスライダー付き計算ツール。",
    icon: "💰",
    path: "/tools/salary-calc",
    category: "お金",
    keywords: ["手取り計算", "給料計算", "年収手取り", "所得税", "住民税"],
    related: ["ideco-calc", "nisa-calc", "furusato-nozei", "tax-calc", "living-cost", "pension-calc"],
  },
  {
    id: "living-cost",
    name: "生活費シミュレーター",
    description: "一人暮らしの月額生活費を項目別にシミュレーション。必要な手取り月収と年収目安もわかる。",
    icon: "🏠",
    path: "/tools/living-cost",
    category: "お金",
    keywords: ["生活費", "一人暮らし費用", "生活費計算", "一人暮らしシミュレーション"],
  },
  {
    id: "pet-cost",
    name: "ペット費用シミュレーター",
    description: "犬・猫を飼う生涯費用を計算。初期費用・月々のエサ代・医療費・トリミング代まで一括シミュレーション。",
    icon: "🐾",
    path: "/tools/pet-cost",
    category: "お金",
    keywords: ["ペット費用", "犬費用", "猫費用", "ペット生涯費用", "ペット飼育費"],
  },
  {
    id: "mobile-savings",
    name: "スマホ料金節約シミュレーター",
    description: "今のスマホ料金と格安SIM・サブブランドを比較。乗り換えで年間いくら節約できるか瞬時に計算。",
    icon: "📱",
    path: "/tools/mobile-savings",
    category: "お金",
    keywords: ["スマホ料金比較", "格安SIM", "スマホ節約", "携帯料金", "ahamo"],
  },
  {
    id: "wedding-cost",
    name: "結婚費用シミュレーター",
    description: "結婚式・披露宴・指輪・新婚旅行・新生活準備の総額を一括計算。ご祝儀との差額や自己負担額もわかる。",
    icon: "💒",
    path: "/tools/wedding-cost",
    category: "お金",
    keywords: ["結婚費用", "結婚式費用", "ウェディング費用", "ご祝儀計算", "結婚式相場"],
  },
  {
    id: "furusato-nozei",
    name: "ふるさと納税シミュレーター",
    description: "ふるさと納税の上限額を年収・家族構成から計算。自己負担2,000円で控除できる最大金額と返礼品価値の目安がわかる。",
    icon: "🎁",
    path: "/tools/furusato-nozei",
    category: "お金",
    keywords: ["ふるさと納税", "ふるさと納税 上限", "ふるさと納税 計算", "控除額計算", "寄附金控除"],
  },
  {
    id: "ideco-calc",
    name: "iDeCo節税シミュレーター",
    description: "iDeCo（個人型確定拠出年金）の年間節税額と60歳時の受取額を計算。会社員・自営業・公務員の掛金上限に対応。",
    icon: "📈",
    path: "/tools/ideco-calc",
    category: "お金",
    keywords: ["iDeCo", "iDeCo節税", "個人型確定拠出年金", "iDeCo計算", "老後資産"],
    related: ["nisa-calc", "pension-calc", "salary-calc", "furusato-nozei", "retirement-calc", "medical-deduction"],
  },
  {
    id: "retirement-calc",
    name: "退職金手取り計算",
    description: "退職金の手取り額を計算。退職所得控除・所得税・住民税を自動計算。勤続年数別の手取り比較も。",
    icon: "💼",
    path: "/tools/retirement-calc",
    category: "お金",
    keywords: ["退職金計算", "退職金 手取り", "退職所得控除", "退職金 税金", "退職金シミュレーション"],
  },
  {
    id: "pension-calc",
    name: "年金受給額シミュレーター",
    description: "年金はいくらもらえる？年収・加入年数・受給開始年齢を入力するだけで老齢基礎年金＋厚生年金の受給額を計算。繰り上げ・繰り下げ比較も。",
    icon: "🏦",
    path: "/tools/pension-calc",
    category: "お金",
    keywords: ["年金計算", "年金受給額", "老齢年金", "年金シミュレーション", "繰り下げ受給"],
  },
  {
    id: "mortgage-deduction",
    name: "住宅ローン控除シミュレーター",
    description: "住宅ローン控除（減税）の節税額を計算。借入額・金利・住宅種別から13年間の控除額合計を算出。2024年税制対応。",
    icon: "🏡",
    path: "/tools/mortgage-deduction",
    category: "お金",
    keywords: ["住宅ローン控除", "住宅ローン減税", "住宅ローン控除 計算", "住宅取得控除", "ローン控除シミュレーション"],
  },
  {
    id: "nisa-calc",
    name: "NISA積立シミュレーター",
    description: "新NISA（2024年〜）の積立シミュレーション。月額・年数・利回りから将来の資産額を計算。非課税効果vs課税口座の比較グラフ付き。",
    icon: "📊",
    path: "/tools/nisa-calc",
    category: "お金",
    keywords: ["NISA積立", "新NISA計算", "NISAシミュレーション", "つみたてNISA", "資産運用計算"],
    related: ["ideco-calc", "pension-calc", "salary-calc", "furusato-nozei", "retirement-calc", "mortgage-deduction"],
  },
  {
    id: "inheritance-tax",
    name: "相続税計算シミュレーター",
    description: "相続税の基礎控除と税額を無料計算。遺産総額・法定相続人数を入力するだけで相続税総額・配偶者控除後の手取りをシミュレーション。税率10〜55%対応。",
    icon: "🏛",
    path: "/tools/inheritance-tax",
    category: "お金",
    keywords: ["相続税計算", "相続税シミュレーション", "相続税 基礎控除", "相続税 いくら", "遺産相続"],
  },
  {
    id: "kokuho-calc",
    name: "国民健康保険料計算",
    description: "フリーランス・自営業・退職後の国民健康保険料を年収から計算。都道府県別料率対応、軽減判定・社会保険との比較も。",
    icon: "🏥",
    path: "/tools/kokuho-calc",
    category: "お金",
    keywords: ["国民健康保険料計算", "国民健康保険 いくら", "フリーランス 保険料", "自営業 健康保険", "退職後 保険料"],
  },
  {
    id: "ikukyu-calc",
    name: "育休給付金シミュレーター",
    description: "産休・育休でいくらもらえる？月収から育児休業給付金を計算。67%/50%の期間別受給額・出産手当金・社会保険料免除も含めた実質受給総額がわかる。",
    icon: "👶",
    path: "/tools/ikukyu-calc",
    category: "お金",
    keywords: ["育休給付金計算", "育児休業給付金", "産休 手当", "育休 いくらもらえる", "パパ育休"],
  },
  {
    id: "medical-deduction",
    name: "医療費控除シミュレーター",
    description: "医療費控除でいくら還付される？年収・医療費を入力するだけで控除額と還付金を計算。セルフメディケーション税制との比較も。2025年確定申告対応。",
    icon: "🏥",
    path: "/tools/medical-deduction",
    category: "お金",
    keywords: ["医療費控除 計算", "医療費控除 いくら戻る", "確定申告 医療費", "医療費控除 シミュレーション", "セルフメディケーション"],
  },
  {
    id: "scholarship-repay",
    name: "奨学金返済シミュレーター",
    description: "奨学金の総返済額・期間を計算。借入総額・月々返済額から繰り上げ返済の節約効果も比較。JASSO第一種・第二種対応。",
    icon: "🎓",
    path: "/tools/scholarship-repay",
    category: "お金",
    keywords: ["奨学金 返済 シミュレーション", "奨学金 総返済額", "奨学金 繰り上げ返済", "奨学金 計算", "JASSO 返済"],
  },
  {
    id: "body-calc",
    name: "体脂肪率・基礎代謝計算",
    description: "体脂肪率・基礎代謝・1日の総消費カロリー（TDEE）を無料計算。目標体重までのダイエット期間・推奨摂取カロリーもシミュレーション。",
    icon: "💪",
    path: "/tools/body-calc",
    category: "計算",
    keywords: ["体脂肪率 計算", "基礎代謝 計算", "TDEE 計算", "ダイエット カロリー計算", "消費カロリー 計算"],
    related: ["bmi-calc", "loan-calc", "electricity-calc"],
  },
  {
    id: "property-tax",
    name: "固定資産税計算シミュレーター",
    description: "固定資産税の年額を無料計算。土地・建物の評価額を入力するだけで税額を算出。住宅用地の軽減措置・新築特例も自動適用。マンション・一戸建て対応。",
    icon: "🏠",
    path: "/tools/property-tax",
    category: "お金",
    keywords: ["固定資産税 計算", "固定資産税 シミュレーション", "固定資産税 いくら", "固定資産税 マンション", "固定資産税 一戸建て"],
    related: ["mortgage-deduction", "loan-calc", "inheritance-tax", "gift-tax", "salary-calc"],
  },
  {
    id: "car-tax",
    name: "自動車税計算シミュレーター",
    description: "自動車税（種別割）を排気量から計算。環境性能割・月割り還付・グリーン化特例も対応。新車・中古車の購入時の税金シミュレーションに。",
    icon: "🚗",
    path: "/tools/car-tax",
    category: "お金",
    keywords: ["自動車税 計算", "自動車税 排気量", "環境性能割 計算", "自動車税 いくら", "エコカー減税"],
  },
  {
    id: "electricity-saving",
    name: "電気代節約シミュレーター",
    description: "節電アクションを選ぶだけで年間削減額を計算。LED交換・エアコン設定・待機電力削減の効果を可視化。CO2削減量も表示。",
    icon: "💡",
    path: "/tools/electricity-saving",
    category: "お金",
    keywords: ["電気代節約", "節電 効果 計算", "電気代 削減", "LED 節約", "電気代 シミュレーション"],
    related: ["electricity-calc", "living-cost", "mobile-savings"],
  },
  {
    id: "gift-tax",
    name: "贈与税計算シミュレーター",
    description: "贈与税の税額を無料計算。年間110万円の基礎控除を超えた分の贈与税を一般税率・特例税率で計算。暦年贈与シミュレーションも。",
    icon: "🎁",
    path: "/tools/gift-tax",
    category: "お金",
    keywords: ["贈与税 計算", "贈与税 シミュレーション", "贈与税 110万", "暦年贈与", "相続税 贈与"],
    related: ["inheritance-tax", "salary-calc", "furusato-nozei"],
  },
  {
    id: "water-bill",
    name: "水道料金計算ツール",
    description: "水道使用量（㎥）から水道料金を計算。東京・大阪など主要都市の料金体系に対応。生活習慣から使用量を推定する機能付き。",
    icon: "💧",
    path: "/tools/water-bill",
    category: "お金",
    keywords: ["水道料金 計算", "水道代 いくら", "水道使用量 計算", "水道代 節約", "水道料金 東京"],
    related: ["electricity-calc", "electricity-saving", "living-cost"],
  },
  {
    id: "childcare-cost",
    name: "保育料シミュレーター",
    description: "認可保育所の月額保育料を年収から計算。3歳以上の幼児教育無償化・副食費・延長保育料も含めた実質負担額をシミュレーション。",
    icon: "👶",
    path: "/tools/childcare-cost",
    category: "お金",
    keywords: ["保育料 計算", "保育料 年収", "保育無償化", "保育料 シミュレーション", "認可保育所 料金"],
    related: ["ikukyu-calc", "salary-calc", "living-cost", "kokuho-calc"],
  },
  {
    id: "compound-interest",
    name: "複利計算シミュレーター",
    description: "複利計算を無料シミュレーション。一括投資・毎月積立の両方に対応。元本・年利・運用期間を入力するだけで将来の資産額をグラフで表示。72の法則も解説。",
    icon: "📈",
    path: "/tools/compound-interest",
    category: "お金",
    keywords: ["複利計算", "積立 シミュレーション", "資産運用 計算", "複利 効果", "将来価値 計算"],
    related: ["nisa-calc", "ideco-calc", "investment-return", "salary-increase", "pension-calc", "retirement-calc"],
  },
  {
    id: "investment-return",
    name: "投資リターン計算",
    description: "投資の利回り・年率リターン（CAGR）を無料計算。購入価格・売却価格・配当金・保有期間から実質リターンを算出。インデックス投資・株式投資の成績評価に。",
    icon: "💹",
    path: "/tools/investment-return",
    category: "お金",
    keywords: ["投資 利回り 計算", "CAGR 計算", "年率リターン", "株式 リターン 計算", "投資信託 利回り"],
    related: ["compound-interest", "nisa-calc", "ideco-calc", "salary-increase"],
  },
  {
    id: "salary-increase",
    name: "昇給シミュレーター",
    description: "昇給後の手取り・生涯年収を無料シミュレーション。現在の年収と昇給率・昇給頻度を入力して将来の給与推移を予測。転職・昇進交渉の判断材料に。",
    icon: "💰",
    path: "/tools/salary-increase",
    category: "お金",
    keywords: ["昇給 シミュレーション", "生涯年収 計算", "年収 推移", "手取り 変化", "転職 年収 比較"],
    related: ["salary-calc", "side-job-tax", "freelance-tax", "compound-interest", "retirement-calc", "ideco-calc"],
  },
  {
    id: "rent-vs-buy",
    name: "賃貸vs購入シミュレーター",
    description: "賃貸と住宅購入の総コストを30年・50年スパンで比較。物件価格・家賃・ローン金利・住居費を入力して生涯コストをシミュレーション。持ち家vs賃貸の損益分岐点を計算。",
    icon: "🏠",
    path: "/tools/rent-vs-buy",
    category: "お金",
    keywords: ["賃貸 vs 購入", "持ち家 賃貸 比較", "住宅購入 シミュレーション", "住居費 計算", "マンション 購入 損得"],
    related: ["mortgage-deduction", "loan-calc", "property-tax", "living-cost", "home-budget"],
  },
  {
    id: "income-tax-calc",
    name: "所得税計算シミュレーター",
    description: "年収・各種控除から所得税を無料計算。給与所得控除・基礎控除・扶養控除・社会保険料控除など控除項目を細かく設定。課税所得と所得税率の内訳も表示。",
    icon: "📋",
    path: "/tools/income-tax-calc",
    category: "お金",
    keywords: ["所得税 計算", "所得税 シミュレーション", "課税所得 計算", "所得税率 計算", "所得税 控除"],
    related: ["salary-calc", "freelance-tax", "tax-calc", "ideco-calc", "medical-deduction", "furusato-nozei"],
  },
  {
    id: "travel-budget",
    name: "旅行予算計算ツール",
    description: "旅行の予算を無料計算。交通費・宿泊費・食費・観光費を入力して合計予算と1人当たりの費用を自動算出。国内旅行・海外旅行の費用シミュレーションに。",
    icon: "✈️",
    path: "/tools/travel-budget",
    category: "生活",
    keywords: ["旅行 予算 計算", "旅行費用 計算", "旅行 費用 シミュレーション", "海外旅行 予算", "国内旅行 費用"],
    related: ["living-cost", "home-budget", "split-bill", "mobile-savings"],
  },
  {
    id: "freelance-tax",
    name: "フリーランス税金シミュレーター",
    description: "フリーランス・個人事業主の税金と手取り額を無料計算。売上・経費・青色申告控除を入力して所得税・住民税・国民健康保険料・国民年金の合計を一括シミュレーション。",
    icon: "💼",
    path: "/tools/freelance-tax",
    category: "お金",
    keywords: ["フリーランス 税金 計算", "個人事業主 手取り", "確定申告 シミュレーション", "フリーランス 所得税", "青色申告 節税"],
    related: ["salary-calc", "kokuho-calc", "side-job-tax", "tax-calc", "ideco-calc", "medical-deduction"],
  },
  {
    id: "depreciation-calc",
    name: "減価償却計算シミュレーター",
    description: "減価償却費を無料計算。定額法・定率法に対応。パソコン・車・建物など資産の取得価額と耐用年数を入力するだけで年度別償却額を一覧表示。確定申告・法人税申告に。",
    icon: "📉",
    path: "/tools/depreciation-calc",
    category: "お金",
    keywords: ["減価償却 計算", "定額法 定率法", "減価償却費 計算", "耐用年数 一覧", "減価償却 シミュレーション"],
    related: ["freelance-tax", "salary-calc", "tax-calc", "property-tax"],
  },
  {
    id: "home-budget",
    name: "家計簿シミュレーター",
    description: "月の収入・支出を入力して家計の収支バランスを診断。住居費・食費・光熱費など項目別に理想割合と比較。節約のヒントと貯蓄シミュレーションも。",
    icon: "📊",
    path: "/tools/home-budget",
    category: "お金",
    keywords: ["家計簿 シミュレーター", "家計 収支 計算", "理想 家計 割合", "家計 診断", "節約 シミュレーション"],
    related: ["salary-calc", "living-cost", "electricity-saving", "loan-calc"],
  },
  {
    id: "calorie-calc",
    name: "カロリー計算・消費カロリー",
    description: "1日の消費カロリー・目標摂取カロリーを無料計算。身長・体重・年齢・活動レベルから基礎代謝（BMR）と総消費エネルギー（TDEE）を算出。ダイエット・筋トレ目標設定に。",
    icon: "🔥",
    path: "/tools/calorie-calc",
    category: "健康",
    keywords: ["カロリー計算", "消費カロリー 計算", "基礎代謝 計算", "ダイエット カロリー", "TDEE 計算"],
    related: ["bmi-calc", "body-calc", "sleep-calc"],
  },
  {
    id: "sleep-calc",
    name: "睡眠時間計算",
    description: "起床時間・就寝時間から最適な睡眠時刻を計算。睡眠サイクル（90分）に基づいてすっきり目覚めるための就寝時刻を提案。理想の睡眠時間・睡眠負債計算も。",
    icon: "😴",
    path: "/tools/sleep-calc",
    category: "健康",
    keywords: ["睡眠時間 計算", "就寝時間 計算", "睡眠サイクル", "起床時間 逆算", "快眠 時間"],
    related: ["calorie-calc", "bmi-calc", "caffeine-calc"],
  },
  {
    id: "caffeine-calc",
    name: "カフェイン摂取量計算",
    description: "1日のカフェイン摂取量を管理。コーヒー・緑茶・エナジードリンクなど飲み物ごとのカフェイン含有量を計算。体重別の安全上限量・睡眠への影響時間も表示。",
    icon: "☕",
    path: "/tools/caffeine-calc",
    category: "健康",
    keywords: ["カフェイン 計算", "コーヒー カフェイン 量", "カフェイン 上限", "カフェイン 半減期", "カフェイン 摂りすぎ"],
    related: ["sleep-calc", "calorie-calc", "bmi-calc"],
  },
];
