export interface Tool {
  id: string;
  name: string;
  description: string;
  icon: string;
  path: string;
  category: string;
  keywords: string[];
}

export const tools: Tool[] = [
  {
    id: "char-counter",
    name: "文字数カウンター",
    description: "テキストの文字数・単語数・行数をリアルタイムでカウント。全角・半角も区別して表示。",
    icon: "Aa",
    path: "/tools/char-counter",
    category: "テキスト",
    keywords: ["文字数カウント", "文字数", "ワードカウント", "文字数チェック"],
  },
  {
    id: "json-formatter",
    name: "JSON整形ツール",
    description: "JSONデータを見やすく整形・検証。シンタックスエラーも即座に検出。",
    icon: "{}",
    path: "/tools/json-formatter",
    category: "開発",
    keywords: ["JSON整形", "JSON検証", "JSONフォーマッター", "JSON変換"],
  },
  {
    id: "qr-generator",
    name: "QRコード生成",
    description: "URLやテキストからQRコードを瞬時に作成。PNG画像でダウンロード可能。",
    icon: "QR",
    path: "/tools/qr-generator",
    category: "画像",
    keywords: ["QRコード作成", "QRコード生成", "QRコード"],
  },
  {
    id: "password-gen",
    name: "パスワード生成",
    description: "安全なランダムパスワードを生成。長さ・文字種をカスタマイズ可能。",
    icon: "PW",
    path: "/tools/password-gen",
    category: "セキュリティ",
    keywords: ["パスワード生成", "ランダムパスワード", "安全なパスワード"],
  },
  {
    id: "base64",
    name: "Base64変換",
    description: "テキストをBase64にエンコード・デコード。日本語も完全対応。",
    icon: "B64",
    path: "/tools/base64",
    category: "開発",
    keywords: ["Base64変換", "Base64エンコード", "Base64デコード"],
  },
  {
    id: "url-encode",
    name: "URLエンコード/デコード",
    description: "URLの特殊文字をエンコード・デコード。日本語URLの変換に便利。",
    icon: "%",
    path: "/tools/url-encode",
    category: "開発",
    keywords: ["URLエンコード", "URLデコード", "パーセントエンコーディング"],
  },
  {
    id: "color-converter",
    name: "カラーコード変換",
    description: "HEX・RGB・HSLを相互変換。カラーピッカーで直感的に色を選択。",
    icon: "C",
    path: "/tools/color-converter",
    category: "デザイン",
    keywords: ["カラーコード変換", "HEX変換", "RGB変換", "色変換"],
  },
  {
    id: "text-diff",
    name: "テキスト差分比較",
    description: "2つのテキストの差分をハイライト表示。変更箇所が一目でわかる。",
    icon: "+-",
    path: "/tools/text-diff",
    category: "テキスト",
    keywords: ["テキスト差分", "テキスト比較", "diff", "文章比較"],
  },
  {
    id: "markdown-preview",
    name: "Markdownプレビュー",
    description: "Markdownをリアルタイムでプレビュー。コピー&ペーストですぐ確認。",
    icon: "MD",
    path: "/tools/markdown-preview",
    category: "テキスト",
    keywords: ["Markdownプレビュー", "マークダウン", "Markdown変換"],
  },
  {
    id: "text-replace",
    name: "テキスト一括置換",
    description: "テキスト内の文字列を一括置換。正規表現にも対応。",
    icon: "ab",
    path: "/tools/text-replace",
    category: "テキスト",
    keywords: ["テキスト置換", "文字列置換", "一括置換", "検索置換"],
  },
  {
    id: "zen-han",
    name: "半角全角変換",
    description: "テキストの半角・全角を一括変換。英数字・記号・スペースに対応。",
    icon: "Ａa",
    path: "/tools/zen-han",
    category: "テキスト",
    keywords: ["半角全角変換", "全角半角", "半角変換", "全角変換"],
  },
  {
    id: "hash-gen",
    name: "ハッシュ生成",
    description: "SHA-1、SHA-256、SHA-512等のハッシュ値をテキストから即座に生成。",
    icon: "#",
    path: "/tools/hash-gen",
    category: "セキュリティ",
    keywords: ["ハッシュ生成", "SHA256", "SHA-1", "ハッシュ値"],
  },
  {
    id: "unix-time",
    name: "Unix時間変換",
    description: "Unixタイムスタンプと日時を相互変換。現在時刻もリアルタイム表示。",
    icon: "T",
    path: "/tools/unix-time",
    category: "開発",
    keywords: ["Unix時間変換", "タイムスタンプ変換", "エポック秒", "UNIX時間"],
  },
  {
    id: "byte-counter",
    name: "バイト数カウント",
    description: "テキストのバイト数をUTF-8、UTF-16、Shift-JISで計算。文字コード判定にも。",
    icon: "01",
    path: "/tools/byte-counter",
    category: "開発",
    keywords: ["バイト数", "文字コード判定", "バイトカウント", "文字コード変換"],
  },
  {
    id: "regex-tester",
    name: "正規表現テスター",
    description: "正規表現パターンをリアルタイムでテスト。マッチ結果をハイライト表示。",
    icon: ".*",
    path: "/tools/regex-tester",
    category: "開発",
    keywords: ["正規表現テスト", "regex", "正規表現チェッカー", "パターンマッチ"],
  },
  {
    id: "html-escape",
    name: "HTMLエスケープ",
    description: "HTML特殊文字をエスケープ・アンエスケープ。XSS対策にも。",
    icon: "<>",
    path: "/tools/html-escape",
    category: "開発",
    keywords: ["HTMLエスケープ", "HTMLアンエスケープ", "特殊文字変換", "XSS対策"],
  },
  {
    id: "word-counter",
    name: "SNS文字数チェッカー",
    description: "Twitter、Instagram、YouTube等の文字数制限をリアルタイムでチェック。",
    icon: "📱",
    path: "/tools/word-counter",
    category: "テキスト",
    keywords: ["SNS文字数", "Twitter文字数", "Instagram文字数", "文字数制限"],
  },
  {
    id: "lorem-ipsum",
    name: "ダミーテキスト生成",
    description: "デザインやレイアウト確認用のダミーテキストを生成。日本語・英語対応。",
    icon: "Tx",
    path: "/tools/lorem-ipsum",
    category: "テキスト",
    keywords: ["ダミーテキスト", "Lorem Ipsum", "テスト文章", "サンプルテキスト"],
  },
  {
    id: "json-to-csv",
    name: "JSON → CSV変換",
    description: "JSON配列をCSV形式に変換。ExcelやGoogleスプレッドシートに貼り付け可能。",
    icon: "📊",
    path: "/tools/json-to-csv",
    category: "開発",
    keywords: ["JSON CSV変換", "JSON to CSV", "JSONからCSV", "データ変換"],
  },
  {
    id: "aspect-ratio",
    name: "アスペクト比計算",
    description: "画像・動画のアスペクト比を計算。SNSや動画サイトの推奨サイズも一覧表示。",
    icon: "⊞",
    path: "/tools/aspect-ratio",
    category: "デザイン",
    keywords: ["アスペクト比", "アスペクト比計算", "画像サイズ", "縦横比"],
  },
  {
    id: "number-converter",
    name: "進数変換",
    description: "2進数・8進数・10進数・16進数を相互変換。プログラミングに便利。",
    icon: "0x",
    path: "/tools/number-converter",
    category: "開発",
    keywords: ["進数変換", "2進数変換", "16進数変換", "基数変換"],
  },
  {
    id: "jwt-decoder",
    name: "JWTデコーダー",
    description: "JWTトークンをHeader・Payload・Signatureに分解してデコード表示。有効期限も確認。",
    icon: "JWT",
    path: "/tools/jwt-decoder",
    category: "開発",
    keywords: ["JWTデコード", "JWT解析", "JWTトークン", "JSON Web Token"],
  },
  {
    id: "cron-parser",
    name: "Cron式解説",
    description: "Cron式を日本語で解説。次の実行予定時刻やよく使うプリセット一覧も表示。",
    icon: "⏰",
    path: "/tools/cron-parser",
    category: "開発",
    keywords: ["Cron式解説", "crontab", "Cron変換", "スケジュール"],
  },
  {
    id: "encoding-detector",
    name: "文字コード判定",
    description: "テキストのバイト列から文字コードを推定。UTF-8、Shift_JIS、EUC-JP対応。16進ダンプ表示。",
    icon: "文",
    path: "/tools/encoding-detector",
    category: "テキスト",
    keywords: ["文字コード判定", "エンコーディング検出", "Shift_JIS判定", "UTF-8判定"],
  },
  {
    id: "ip-info",
    name: "IPアドレス情報",
    description: "IPv4/IPv6のクラス判定、CIDR計算、サブネット情報、バイナリ表現を表示。",
    icon: "IP",
    path: "/tools/ip-info",
    category: "開発",
    keywords: ["IPアドレス計算", "CIDR計算", "サブネット計算", "ネットワーク計算"],
  },
  {
    id: "uuid-gen",
    name: "UUID生成",
    description: "UUID（GUID）をワンクリックで生成。v4ランダムUUIDを一括生成。コピー可能。",
    icon: "ID",
    path: "/tools/uuid-gen",
    category: "開発",
    keywords: ["UUID生成", "GUID生成", "ランダムID", "ユニークID"],
  },
  {
    id: "csv-to-json",
    name: "CSV → JSON変換",
    description: "CSVデータをJSON形式に変換。ヘッダー自動検出、区切り文字指定対応。",
    icon: "📋",
    path: "/tools/csv-to-json",
    category: "開発",
    keywords: ["CSV JSON変換", "CSV to JSON", "CSVからJSON", "データ変換"],
  },
  {
    id: "yaml-json",
    name: "YAML ⇔ JSON変換",
    description: "YAMLとJSONを相互変換。Docker Compose・Kubernetes設定ファイルの変換に。",
    icon: "YJ",
    path: "/tools/yaml-json",
    category: "開発",
    keywords: ["YAML変換", "YAML JSON", "YAML to JSON", "設定ファイル変換"],
  },
  {
    id: "sql-formatter",
    name: "SQL整形",
    description: "SQLクエリを見やすく整形・フォーマット。インデント付きで可読性アップ。",
    icon: "SQL",
    path: "/tools/sql-formatter",
    category: "開発",
    keywords: ["SQL整形", "SQLフォーマッター", "SQL beautify", "クエリ整形"],
  },
  {
    id: "css-minify",
    name: "CSS圧縮・整形",
    description: "CSSを圧縮（ミニファイ）して軽量化、または整形して可読性向上。削減率も表示。",
    icon: "CSS",
    path: "/tools/css-minify",
    category: "開発",
    keywords: ["CSS圧縮", "CSSミニファイ", "CSS整形", "CSS minify"],
  },
  {
    id: "emoji-search",
    name: "絵文字検索",
    description: "絵文字を日本語キーワードで検索してワンクリックコピー。SNS・チャットに便利。",
    icon: "😀",
    path: "/tools/emoji-search",
    category: "テキスト",
    keywords: ["絵文字検索", "emoji検索", "絵文字コピー", "顔文字"],
  },
  {
    id: "timestamp-calc",
    name: "日時計算",
    description: "日付の差分計算、日数の加算・減算。経過日数・残り日数の確認に。",
    icon: "📅",
    path: "/tools/timestamp-calc",
    category: "開発",
    keywords: ["日付計算", "日数計算", "日時差分", "経過日数"],
  },
  {
    id: "slug-gen",
    name: "スラッグ生成",
    description: "テキストからURL用のスラッグを生成。SEOに最適なURLを簡単作成。",
    icon: "🔗",
    path: "/tools/slug-gen",
    category: "開発",
    keywords: ["スラッグ生成", "URL slug", "SEO URL", "パーマリンク"],
  },
  {
    id: "text-escape",
    name: "文字列エスケープ",
    description: "JSON・JavaScript・SQL・CSV・XMLの文字列エスケープ・アンエスケープ。",
    icon: "\\",
    path: "/tools/text-escape",
    category: "開発",
    keywords: ["文字列エスケープ", "JSONエスケープ", "SQLエスケープ", "エスケープ変換"],
  },
  {
    id: "html-to-md",
    name: "HTML → Markdown変換",
    description: "HTMLコードをMarkdown形式に変換。ブログ移行やドキュメント変換に便利。",
    icon: "H→M",
    path: "/tools/html-to-md",
    category: "テキスト",
    keywords: ["HTML Markdown変換", "HTMLからMarkdown", "HTML to MD", "マークダウン変換"],
  },
];
